CREATE TABLE IF NOT EXISTS zones(
zone_id SERIAL PRIMARY KEY,
location VARCHAR(50) NOT NULL,
name VARCHAR(10) NOT NOT NULL ,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blocks(
block_id SERIAL PRIMARY KEY,
zone_id SERIAL REFERENCES zones(zone_id) ON delete cascade ,
name VARCHAR(50) NOT NULL,
capacity INTEGER NOT NULL,
available_spaces INTEGER ,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cars(
car_id SERIAL PRIMARY KEY,
block_id   SERIAL REFERENCES blocks(block_id) ON delete cascade ,
plate_str  VARCHAR(20) NOT NULL UNIQUE ,
park_date  VARCHAR(20) NOT NULL ,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
